name: segmentation
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.9.30=h06a4308_1
  - certifi=2021.10.8=py37h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.0.1=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - albumentations==1.0.3
    - anyio==3.3.3
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.14.6
    - charset-normalizer==2.0.7
    - click==8.0.3
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.24
    - debugpy==1.5.0
    - decorator==5.1.0
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - efficientnet-pytorch==0.6.3
    - entrypoints==0.3
    - gitdb==4.0.7
    - gitpython==3.1.24
    - idna==3.3
    - imageio==2.9.0
    - importlib-metadata==4.8.1
    - install==1.3.4
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.2
    - json5==0.9.4
    - jsonschema==4.1.0
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyter-server==1.11.1
    - jupyterlab==3.1.18
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - munch==2.5.0
    - nbclassic==0.3.2
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.6.3
    - notebook==6.4.4
    - numpy==1.21.2
    - opencv-python==4.2.0.34
    - opencv-python-headless==4.5.3.56
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.3.2
    - pretrainedmodels==0.7.4
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.20
    - protobuf==3.18.1
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pycocotools==2.0.2
    - pycparser==2.20
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - requests==2.26.0
    - requests-unixsocket==0.2.0
    - scikit-image==0.18.3
    - scipy==1.7.1
    - seaborn==0.11.2
    - segmentation-models-pytorch==0.1.3
    - send2trash==1.8.0
    - sentry-sdk==1.4.3
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==4.0.0
    - sniffio==1.2.0
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - tifffile==2021.10.12
    - timm==0.3.2
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - tornado==6.1
    - tqdm==4.28.1
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - wandb==0.12.4
    - wcwidth==0.2.5
    - webcolors==1.11.1
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - widgetsnbextension==3.5.1
    - yaspin==2.1.0
    - zipp==3.6.0
prefix: /opt/conda/envs/segmentation
